from pandas import DataFrame
from ..globals.constants import BINANCE_COL_NAMES, DAILY_COL_NAMES

def prepare_daily_data_for_modeling(df: DataFrame) -> DataFrame:
  return df.drop(columns=[
    BINANCE_COL_NAMES['OPEN_TIME'],
    BINANCE_COL_NAMES['HIGH_PRICE'],
    BINANCE_COL_NAMES['LOW_PRICE'],
    BINANCE_COL_NAMES['OPEN_PRICE'],
    BINANCE_COL_NAMES['VOLUME'],
    BINANCE_COL_NAMES['NUMBER_OF_TRADES'],
    BINANCE_COL_NAMES['TAKER_BUY_BASE_VOLUME'],
    DAILY_COL_NAMES['SMA_3'],
    DAILY_COL_NAMES['SMA_7'],
    DAILY_COL_NAMES['SMA_20'],
    DAILY_COL_NAMES['EMA_3'],
    DAILY_COL_NAMES['EMA_7'],
    DAILY_COL_NAMES['EMA_20'],
    DAILY_COL_NAMES['RSI_14'],
    DAILY_COL_NAMES['BBU_20'],
    DAILY_COL_NAMES['BBL_20'],
    DAILY_COL_NAMES['MACD_LINE'],
    DAILY_COL_NAMES['MACD_SIGNAL_LINE'],
    DAILY_COL_NAMES['MACD_HISTOGRAM'],
    DAILY_COL_NAMES['TR_CURRENT'],
    DAILY_COL_NAMES['ATR_14'],
    DAILY_COL_NAMES['OBV'],
    DAILY_COL_NAMES['MOMENTUM_10'],
    DAILY_COL_NAMES['ROC_14'],
    DAILY_COL_NAMES['WILLR_14'],
    DAILY_COL_NAMES['STOCH_K'],
    DAILY_COL_NAMES['STOCH_D'],
    DAILY_COL_NAMES['PERCENT_CHANGE'],
])
